Force the crate-type to rlib
It was failing like so:

    error: language item required, but not found: `panic_fmt`
    error: language item required, but not found: `stack_exhausted`
    error: language item required, but not found: `eh_personality`

Since this is a pure macro plugin, it doesn't need to build a proper
library with these lang items.  An rlib suffices.